### ISSUE TITLE
Avoid syscalls

### ISSUE THREAD

**Issue by mccoyst** [eaburns/Watch#22]
These aren't covered by the Go compatibility promise and are questionably portable. I at least want to get rid of the Wait4 polling, because it's orthogonal to the race described in #14 (which was due to global PID flim-flammery).

**Comment by eaburns** [comment]
The race fixed by Wait4 is between wait and kill, not the pids. You don't
want to send kill to a process after wait has returned, because then you
may kill a different process which was unlucky enough to get allocated that
same pid. With the polling scheme, kill is only ever sent if wait has yet
to return the process exit status, so you are always killing the intended
process.

**Comment by mccoyst** [comment]
We should use Cmd.Kill instead of a kill that takes a PID.

**Comment by eaburns** [comment]
Does that kill the whole process group?

**Comment by mccoyst** [comment]
No, but I think that's a hopeless road to go down… Nothing stops the subprocesses from going into disjoint groups (and again, portability). I'll understand if that's a dealbreaker for you, though.

**Comment by eaburns** [comment]
It's a deal breaker. Nothing stops it, but it also doesn't happen. Build
processes aren't creating daemons, but they may fork off.

I'm not concerned about system call API stability. If wait4 changes (it
won't), we'll fix it. I'm also not overly concerned with portability. It
works on Linux, and you indicate that it works on osx. That's good enough
for me. If it works on BSD or Windows, great, but I'm not going to break
one of my most heavily used tools for myself to cater to those systems.

**Comment by mccoyst** [comment]
No problem, but FYI the compatibility promise isn't that wait4 may change, but that syscall.Wait4 may be removed at any time.

**Comment by eaburns** [comment]
It'll be fine. If it goes away well use cgo :-)
