### ISSUE TITLE
-x only works for directories

### ISSUE THREAD

**Issue by sqweek** [eaburns/Watch#25]
eg. with no exclusions, `Watch -v -t echo build`

`touch .git/newfile` => causes build
`touch .gitignore` => causes build

Now try `Watch -v -t -x '.git.*' echo build`
Debug output says:

    2015/08/27 14:15:36 DEBUG: excluding .git
    2015/08/27 14:15:36 DEBUG: excluding .gitignore

but then:

`touch .gitignore` => causes build

`touch .git/newfile` is however correctly ignored.

**Comment by sqweek** [comment]
I delved into inotify recently which made me understand why this happens - the change to .gitignore also results in a change to the current directory, which we ARE listening to. Directory events include the name of the affected file though, so the exclusion regexp can be reapplied while handling the event to ignore the change:

```
diff --git a/main.go b/main.go
index 09fa756..e16d6d2 100644
--- a/main.go
+++ b/main.go
@@ -212,6 +212,10 @@ func sendChanges(w *fsnotify.Watcher, changes chan<- time.Time) {
                        log.Fatalf("Watcher error: %s\n", err)
 
                case ev := <-w.Events:
+                       if excludeRe != nil && excludeRe.MatchString(ev.Name) {
+                               debugPrint("ignoring event for excluded %s", ev.Name)
+                               continue
+                       }
                        time, err := modTime(ev.Name)
                        if err != nil {
                                log.Printf("Failed to get even time: %s", err)
```

Which I think provides the intuitive behaviour.

**Comment by eaburns** [comment]
I think that's right. Can you please send a pull request?
